# Generated by Django 4.0.6 on 2022-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_post_options_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
