# Generated by Django 4.0.6 on 2022-09-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='upload', upload_to=''),
        ),
    ]
